### ISSUE TITLE
[Feature Request] Allows configuration to ignore files in node_modules

### ISSUE THREAD

**Issue by lc-soft** [Silksofthesoul/vite-plugin-transform#1]
Some js files in the `node_modules` directory will contain the string `#{`, for example:

```js
[/#{/, { cases: { '$S2=="': { token: "string", next: "root.interpolatedstring" }, "@default": "string" } }], [/["']/, { cases: { "$#==$S2": { token: "string", next: "@pop" }, "@default": "string" } }], [/#/, "string"]], herestring: [[/("""|''')/, { cases: { "$1==$S2": { token: "string", next: "@pop" }, "@default": "string" } }], [/[^#\\'"]+/, "string"], [/['"]+/, "string"], [/@escapes/, "string.escape"], [/\./, "string.escape.invalid"], [/#{/, { token: "string.quote", next: "root.interpolatedstring" }]};
```

It will be transformed to:

```js
[//, { token: "string.quote", next: "root.interpolatedstring" }]};
```

This causes Vite to throw an error:

```text
[vite] Internal server error: Failed to parse source for import analysis because the content contains invalid JS syntax. If you are using JSX, make sure to name the file with the .jsx or .tsx extension.
```

Therefore, I recommend adding a configuration item like `exclude` to allow the user to set the plugin to ignore files in the `node_modules` directory.

**Comment by Silksofthesoul** [comment]
@lc-soft Hello! Thank you for create this Feature Request.
I added the configuration item 'exclude' option, now you can set up ignore files. 
https://github.com/Silksofthesoul/vite-plugin-transform#exclude

Changes can be found in the latest version of the plugin.
