### ISSUE TITLE
Include an XML file in the build output after transforming

### ISSUE THREAD

**Issue by Shujee** [Silksofthesoul/vite-plugin-transform#3]
I'm trying to bundle an XML file in the production build. Some transformation needs to be applied on the file before spitting it out. Unfortunately, it doesn't seem to touch XML files in any way. If I put my XML file in public folder, it gets copied to the build output, but is not processed by this plugin. If I put it in assets or somewhere else under src, it is simply ignored.

How can I ask Vite to include certain file(s) in the build output and pass it through transformation?

**Comment by Silksofthesoul** [comment]
Hello! Thank you for your patience. I'll see what I can do and write to you.

**Comment by Silksofthesoul** [comment]
@Shujee
Hello! Try to use version v1.2.1

And in the configuration, add the key "replaceFiles" with an array of those files that need to be transformed.
```javascript
const replaceFiles = [
  resolve(join(__dirname, './dist/data.xml')),
  resolve(join(__dirname, './dist/data-notimported.xml')),
];
```

Also, I updated the documentation and created a repository where you can check out the example:
https://github.com/Silksofthesoul/vite-plugin-transform-examples

**Comment by Shujee** [comment]
Works like a charm. Bundle of thanks (without any transform, lol).
