### ISSUE TITLE
When this plugin is enabled it corrupts the JS sourcemaps

### ISSUE THREAD

**Issue by usizu** [Silksofthesoul/vite-plugin-transform#4]
When I have the plugin enabled in my vite.config.js file, then the JS source maps that are generated on build are broken.

I get this error on the build step: `[plugin transformPlugin] Sourcemap is likely to be incorrect: a plugin (transformPlugin) was used to transform files, but didn't generate a sourcemap for the transformation. Consult the plugin documentation for help`

I have a very minimal transform, which works well (that I wasn't able to get working with the other vite html plugins). 

```js
  plugins: [
    transformPlugin({
      callbackArray: [(code) => code.replace("%{spa_template}%", spa_template)],
    }),
  ]
```

However unfortunately the JS sourcemap file that my project generates is usually a 1.3MB file. When the transformPlugin is enabled and this error is shown, it instead generates a 224bytes file without the correct mappings.

**Comment by Silksofthesoul** [comment]
Hello @usizu . I can suggest changing the keys
`tStart` and `tEnd` to another value.

```javascript
plugins: [
    tStart : '$#TAGSDISABLE',
    tEnd: 'TAGSDISABLE$#',
    transformPlugin({
      callbackArray: [(code) => code.replace("%{spa_template}%", spa_template)],
    }),
  ]
```

Perhaps this method will correct the situation.
